### ISSUE TITLE
Cant execute other command

### ISSUE THREAD

**Issue by ripper66** [joaomatosf/jexboss#1]
Hi,

Got an error while executing other command like 'cd' or any other command.

**Comment by joaomatosf** [comment]
Hello,

Please try again. An external component that is deployed within the vulnerable
server was offline.

2015-04-15 3:29 GMT-03:00 ripper66 <notifications@github.com>:

> Hi,
>
> Got an error while executing other command like 'cd' or any other command.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joaomatosf/jexboss/issues/1>.
>



-- 
João F M Figueiredo
http://lattes.cnpq.br/9638348593991566
