### ISSUE TITLE
Proxy feature request

### ISSUE THREAD

**Issue by riramar** [joaomatosf/jexboss#21]
Estou recebendo connection timed out provavelmente porque da maquina que estou executando só consigo acessar internet via proxy.
Achei que usando a opção "-D" iria evitar o erro abaixo mas recebei o mesmo erro. Esta opção não deveria evitar de fazer a chamada para http://joaomatosf.com/rnp/releases.txt?
Na verdade então essa issue é uma feature request para implementar suporte a proxy.

```
Traceback (most recent call last):
  File "jexboss.py", line 551, in <module>
    main()
  File "jexboss.py", line 367, in main
    updates = check_updates()
  File "E:\jexboss\_updates.py", line 107, in check_updates
    r = pool.request('GET', url, redirect=False, headers=header)
  File "E:\Python27\lib\site-packages\urllib3\request.py", line 66, in request
    **urlopen_kw)
  File "E:\Python27\lib\site-packages\urllib3\request.py", line 87, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "E:\Python27\lib\site-packages\urllib3\poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "E:\Python27\lib\site-packages\urllib3\connectionpool.py", line 671, in urlopen
    release_conn=release_conn, **response_kw)
  File "E:\Python27\lib\site-packages\urllib3\connectionpool.py", line 671, in urlopen
    release_conn=release_conn, **response_kw)
  File "E:\Python27\lib\site-packages\urllib3\connectionpool.py", line 671, in urlopen
    release_conn=release_conn, **response_kw)
  File "E:\Python27\lib\site-packages\urllib3\connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "E:\Python27\lib\site-packages\urllib3\util\retry.py", line 303, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='joaomatosf.com', port=80): Max retries exceeded with url: /rnp/releases.txt (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000000000357A518>, 'Connection to joaomatosf.com timed out. (connect timeout=3.0)'))
```

**Comment by joaomatosf** [comment]
Fala iramar,

Na realidade, a opção -D desabilita um checagem por updates que é realizada pelo webshell jsp implantando dentro do servidor explorado (o webshell jsp verifica se há neste link: http://webshell.jexboss.net/jsp_version.txt) , e não a checagem realizada pelo tool client. 
Várias pessoas já pediram tbm para desabilitar essa checagem realizada pelo tool client (assim como você), de forma que eu iria adicionar uma opção diferente para isso. No entanto, para evitar que fique confuso, vou alterar a opção -D para desativar as duas checagem - e deixar um esclarecimento no help. Em alguns minutos realizo esse commit.
A opção de suporte a proxy irei providenciar tbm :D.

Novamente, vlw pelo report. =]

**Comment by joaomatosf** [comment]
Iramar, commit realizado. Pode verificar se resolveu, por favor?
Thanks

**Comment by riramar** [comment]
Fiz dois testes com "-D" e sem os dois com o mesmo resultado onde o script fica travado logo de cara.

$ python jexboss.py -host http://hostname.com

Depois de um se dou dois enters ele retorna a saída esperada.
Se quiser reproduzir bloqueia acesso a qualquer host com iptables e libera só para o proxy.
Outra feature interessante seria poder incluir cabeçalhos nas requests. Isso ajuda caso o server tenha basic authentication configurado direto no Apache.

**Comment by joaomatosf** [comment]
Eu havia testado com o iptables e deu o resultado esperado aqui... Tu está rodando ele no Windows? No windows nunca fiz testes (apenas contra windows)... Quando tu diz que ele fica travado logo de cara, significa que ele está parado, aguardando o response (até dar timeout)? No fix que liberei ontem, mesmo sem o -D, ele deve capturar o timeout exception e continuar a execução.
Tu está testando um host externo, que precisaria passar pelo proxy, ou rede privada? Se for o primeiro caso, então deveria receber um timeout tbm.
Vlw

**Comment by joaomatosf** [comment]
OBS: hoje a tarde devo testar e, se for tudo certo, libero o suporte a proxy http e socks...

**Comment by riramar** [comment]
Estou rodando o script em uma máquina Windows no Git Bash em uma rede privada sem roteamento para internet. Só sai via proxy. O host alvo esta na internet.
Quando executo o comando simplesmente não retorna nada. Deixa lá parado por uns 10 minutos. Se dou dois enters ele exibe os resultados. Eu imaginava que você estava usando o proxy definido nas variáveis de ambiente do bash ou algo assim.
Se poder explicitar o proxy na linha de comando fica melhor eu acredito.
Depois que implementar da um toque aqui que eu testo na minha instância.

**Comment by joaomatosf** [comment]
Fala iramar,

Adicionei a opção de proxy, mas ainda não commitei. Instalei um windão aqui com git bash e notei que, na verdade, essa "travada" que está ocorrendo aí é na função input, quando o script pergunta ao usuário se deseja ou não explorar (input("   yes/NO ? ")). No caso, o git bash não está fazendo o flush do display. Então, quando vc tecla alguns enters, por padrão a opção "NO" é escolhida e, assim, o script termina (e, finalmente, ocorre o flush do display). 
Vou liberar o commit do support a proxy junto com um fix para esse probleminha e te aviso...

**Comment by joaomatosf** [comment]
OBS: 
Você também pode rodar o python com o argumento -u, de forma a desabilitar o buffer do stdout. Isso deve resolver o problema dessa congelada...
eg.
python -u jexboss.py -host http://target

**Comment by riramar** [comment]
Legal! Depois vou testar e te falo.

**Comment by riramar** [comment]
Com o -u funcionou perfeitamente. :)

**Comment by joaomatosf** [comment]
Jóia, vlw por testar =D. Fiz o commit do suporte ao proxy tbm.

**Comment by riramar** [comment]
Testei aqui com o proxy e ta funcionando! Pode fechar a issue.
Segue mais uma sugestão. Incluir opção -H para adicionar headers.
