### ISSUE TITLE
SSL error may not related, just for sharing

### ISSUE THREAD

**Issue by shaolinint** [joaomatosf/jexboss#34]
OpenSSL::SSL::SSLError SSL_connect returned=1 errno=0 state=error: dh key too small

**Comment by joaomatosf** [comment]
Hi dear,

Sorry for the delay.

This usually occurs when your server uses a cipher no longer supported by your urllib3 client in python.
There are some workarounds. The easiest solution (in my opinion) is to simply install OWASP ZAP and use the following parameters in JexBoss:

--proxy http://127.0.0.1:8080

This will make JexBoss use OWASP ZAP as a proxy - which probably supports a larger set of ciphers than the urllib3 lib.

Thank you for sharing.

Best regards,
