### ISSUE TITLE
You need to set up an Authoritative DNS and try to get the    output of the commands via DNS covert channel

### ISSUE THREAD

**Issue by xotxa** [joaomatosf/jexboss#35]
hello author.
I see this message
"Could not get command output. You need to set up an Authoritative DNS and try to get the
   output of the commands via DNS covert channel"

how can I slove that problem?
thanks you.

**Comment by said708** [comment]
yes   i have  the  same  problem  and  i want  to  solve it

**Comment by joaomatosf** [comment]
This usually occurs when there is a mechanism blocking the responses of your server (like IPS / WAF). In this case, you need to try to validate the vulnerability via dns covert channel (just a suggestion).

You can also try to make a request for your test box and see if it arrives. For example:

`--cmd 'curl http://your_test_box'`

Best regards,
