### ISSUE TITLE
An error occurred while connecting to the host 

### ISSUE THREAD

**Issue by Hemza** [joaomatosf/jexboss#36]
Hello
I've get this error while  checking the server ::

[*] Checking Servlet Deserialization:      
 * An error occurred while connecting to the host @ip:80 (HTTPConnectionPool(host='jst11.azurewebsites.net', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f2a1f585450>, 'Connection to jst11.azurewebsites.net timed out. (connect timeout=1.0)')))

 [*] Checking Application Deserialization:  
 * An error occurred while connecting to the host @ip:80 (HTTPConnectionPool(host='jst11.azurewebsites.net', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f2a1f585510>, 'Connection to jst11.azurewebsites.net timed out. (connect timeout=1.0)')))

**Comment by joaomatosf** [comment]
Hi dear, 

Timeout usually occurs when an IPS / WAF is blocking your requests.

Best regards,
