### ISSUE TITLE
SSL Issue

### ISSUE THREAD

**Issue by ghost** [joaomatosf/jexboss#39]
I'm getting the following SSL issue. Any way to fix this?

```
 [*] Checking JMXInvokerServlet:
 *** An error occurred while connecting to the host https://example.com/ ([SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:661))**
```

**Comment by joaomatosf** [comment]
Hi dear,

Sorry for the delay.

This usually occurs when your server uses a cipher no longer supported by your urllib3 client in python. 
There are some workarounds. The easiest solution (in my opinion) is to simply install OWASP ZAP and use the following parameters in JexBoss:

`--proxy http://127.0.0.1:8080`

This will make JexBoss use OWASP ZAP as a proxy - which probably supports a larger set of ciphers than the urllib3 lib.

Best regards,
