### ISSUE TITLE
generating false positives with a malformed http response

### ISSUE THREAD

**Issue by nibbler3465** [joaomatosf/jexboss#4]
running Python 2.7, the following line returns a r.status of 200 
https://github.com/joaomatosf/jexboss/blob/master/jexboss.py#L120

in certain cases, hosts listening on port 80 do not handle the HEAD request nicely and return a garbage response. It looks like Python 2 is doing this, while Python 3 will see the correct response and generate an exception

In 2.7: 
```
>>> r = pool.request('HEAD', url +str(paths['admin-console']), redirect=False, headers=headers)
>>> r.status
200
```

In 3.4: 
```
>>> r = pool.request('HEAD', url +str(paths['admin-console']), redirect=False, headers=headers)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 331, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 516, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 333, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.4/http/client.py", line 1171, in getresponse
    response.begin()
  File "/usr/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.4/http/client.py", line 333, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine:  Ú¬LIP�=¶<��Þ�brÄ¸�¢nÆGÕc¡»�6Fh¶ñ?àTáÿ»�¾îr»0á�÷<}�Ù6¯�õ¢+àÑÎgìmºc¸ÉfDåÒ��Áþ×�]êÓh¹��ôÕ
```

**Comment by joaomatosf** [comment]
Hello Friend,
Thank you for bug feedback.

Apparently this error occurs when you try to access a door with TLS / SSL but specifies the HTTP (instead of HTTPS) or inform the desired protocol ...
I'm conducting tests to cover other cases of this error and provide the correction.

Thank you.

**Comment by joaomatosf** [comment]
Hello friends,

I made an update to avoid some false positives. Please check if the new version solved the problem.

Thanks for feeback.
