### ISSUE TITLE
SSL Certificate Verification Warning Messages

### ISSUE THREAD

**Issue by kongwenbin** [joaomatosf/jexboss#43]
Is anyone having the same error messages as follow? 

```
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:843: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
```
Based on the recommended [URL](https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings), I added the disable warning message (not recommended of course) but am still seeing a horde of the warning messages. Any idea?

```
import urllib3
urllib3.disable_warnings()
```
![image](https://user-images.githubusercontent.com/3257054/33591676-c5ae42f6-d9c1-11e7-95e5-48b7a98691fa.png)

**Comment by riramar** [comment]
Have you checked this link below?
https://stackoverflow.com/questions/27981545/suppress-insecurerequestwarning-unverified-https-request-is-being-made-in-pytho

```
Update (2017-07-28): If you're using a modern version of these libraries, they may no longer be vendored. If that's the case, then you'll only need to do:

import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
If you're still using a version of Requests which vendors urllib3 inside of it (like the original question), then you can use the original answer below:

Original answer:

The reason doing urllib3.disable_warnings() didn't work for you is because it looks like you're using a separate instance of urllib3 vendored inside of requests.

I gather this based on the path here: /usr/lib/python2.6/site-packages/requests/packages/urllib3/connectionpool.py

To disable warnings in requests' vendored urllib3, you'll need to import that specific instance of the module:

import requests
from requests.packages.urllib3.exceptions import InsecureRequestWarning

requests.packages.urllib3.disable_warnings(InsecureRequestWarning)
```

**Comment by kongwenbin** [comment]
Good catch there @riramar . I can't verify this at the moment but seems like adding `urllib3.exceptions.InsecureRequestWarning` to the function should stop the warning messages from appearing. I'll test it out later.

**Comment by kongwenbin** [comment]
Closing this as it has been verified to be working, the warning messages will not appear now, thanks @riramar
