### ISSUE TITLE
Runtime Error Message on Default Kali 2016

### ISSUE THREAD

**Issue by CoyoteSec** [joaomatosf/jexboss#8]
When running on the default Kali 2016 install (or Ubuntu derivatives, etc.) The following error message is seen:

```
Traceback (most recent call last):
  File "jexboss.py", line 23, in <module>
    from idlelib.ColorDelegator import prog
ImportError: No module named idlelib.ColorDelegator
```
This is a dependency issue (https://pypi.python.org/pypi/cricket/0.2.3). Kali and Ubuntu’s packaging of Python omits the idlelib library from it’s base package.

Users can install idlelib by running:
```
$ sudo apt-get install idle-python2.7
```

**Comment by joaomatosf** [comment]
Hello friends,

  Thanks for the feedback.

  In fact, the idlelib package was included as a dependency for an error. This package is not needed and the latest version at github already makes the correction (deleting the line 23).
  Who are facing the mentioned error, please perform the upgrade or simply delete the line 23.

  Please forgive me for this error.

Regards,

**Comment by CoyoteSec** [comment]
Awesome, thanks!
