### ISSUE TITLE
import urllib3.disable_warnings error with the latest urllib3

### ISSUE THREAD

**Issue by sundw2014** [joaomatosf/jexboss#9]

**Comment by joaomatosf** [comment]
Hello Friend,

You can paste the error section displayed? I tried to reproduce the problem in kali 2016.1 and OS X, but the error did not occur ...

If possible, tell me the version of python and urllib3  where the error occurred:

example:

#python
>>> import urllib3, sys
>>> urllib3.__version__
>>> sys.version_info

Thanks

**Comment by sundw2014** [comment]
```python
>>> urllib3.__version__
'1.7.1'
>>> sys.version_info
sys.version_info(major=3, minor=4, micro=3, releaselevel='final', serial=0)
```

**Comment by HazCod** [comment]
Same here for 2.x and 3.x;

```
>>> urllib3.__version__
'1.7.1'
>>> sys.version_info
sys.version_info(major=2, minor=7, micro=6, releaselevel='final', serial=0)
```

```
>>> import urllib3,sys
>>> urllib3.__version__
'1.7.1'
>>> sys.version_info
sys.version_info(major=3, minor=4, micro=3, releaselevel='final', serial=0)

```

**Comment by joaomatosf** [comment]
Hello Friend,

Sorry for the long time to fix this bug.

The 1.0.14 version contains this fix. 

Thank you for feedback.
